services:
  - type: web
    name: wellbodyvital-platform
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
